# Generated by Django 6.0.7 on 2026-09-05 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='geteaway_response',
            new_name='gateway_response',
        ),
    ]
