# Generated by Django 6.0.7 on 2026-07-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_product',
            old_name='images',
            new_name='image',
        ),
    ]
