# Generated by Django 6.0.7 on 2026-09-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_condition_shop_product_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
